import { FactCheck, Course } from '../types';

export const mockFactChecks: FactCheck[] = [
  {
    id: '2508141650',
    title: 'المئذنة تحت النار: ماذا جرى في مسجد السويداء الكبير؟',
    summary: 'انتشر مقطع فيديو يظهر مسلحين يعتدون على أحد المساجد في السويداء عبر صفحة (اللجاة 24) المحلية، وذلك يوم الأربعاء 13 آب/ أغسطس 2025. يبدو في المقطع تجمع مسلحين حول مسجد السويداء الكبير، مما أثار جدلاً واسعاً حول صحة هذه المعلومات.',
    verdict: 'misleading',
    subVerdict: 'تضليل',
    subVerdictExplanation: 'المحتوى الذي يتضمن مزيجاً من الحقائق والأكاذيب.',
    image: 'https://images.pexels.com/photos/1202723/pexels-photo-1202723.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-14',
    category: 'أخبار محلية',
    readTime: '6 دقائق',
    tags: ['السويداء', 'مسجد', 'اعتداء', 'فيديو'],
    views: 15680,
    featured: true
  },
  {
    id: '2508131650',
    title: 'لا صحة لادعاء إغلاق منفذ القائم الحدودي بين العراق وسوريا',
    summary: 'تداولت منصات التواصل الاجتماعي ادعاءات حول إغلاق منفذ القائم الحدودي بين العراق وسوريا لأسباب أمنية، لكن المصادر الرسمية نفت هذه المعلومات وأكدت استمرار العمل بشكل طبيعي.',
    verdict: 'false',
    subVerdict: 'كذب',
    subVerdictExplanation: 'المحتوى الذي يتعارض بالكامل مع حقائق مثبتة وجرى تأليفه بالكامل ولا أساس له من الصحة.',
    image: 'https://images.pexels.com/photos/4792073/pexels-photo-4792073.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-13',
    category: 'سياسة',
    readTime: '4 دقائق',
    tags: ['منفذ القائم', 'العراق', 'سوريا', 'حدود'],
    views: 12450,
    featured: false
  },
  {
    id: '2508131651',
    title: 'هل أعلن تنظيم "داعش" عن قتلاه في معارك السويداء الأخيرة؟',
    summary: 'انتشرت ادعاءات حول إعلان تنظيم "داعش" عن عدد قتلاه في المعارك الأخيرة في السويداء، لكن التحقق أثبت أن هذه المعلومات كاذبة ولم يصدر أي إعلان رسمي من التنظيم.',
    verdict: 'false',
    subVerdict: 'كذب',
    subVerdictExplanation: 'المحتوى الذي يتعارض بالكامل مع حقائق مثبتة وجرى تأليفه بالكامل ولا أساس له من الصحة.',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-13',
    category: 'أخبار محلية',
    readTime: '5 دقائق',
    tags: ['داعش', 'السويداء', 'معارك', 'إعلان'],
    views: 9870,
    featured: false
  },
  {
    id: '2508131652',
    title: 'هل قتلت قوات أمنية سورية مطران حماة نيقولا بعلبكي؟',
    summary: 'تداولت منصات التواصل الاجتماعي ادعاءات حول مقتل مطران حماة نيقولا بعلبكي على يد قوات أمنية سورية، لكن التحقق أثبت أن هذه المعلومات كاذبة وأن المطران على قيد الحياة.',
    verdict: 'false',
    subVerdict: 'كذب',
    subVerdictExplanation: 'المحتوى الذي يتعارض بالكامل مع حقائق مثبتة وجرى تأليفه بالكامل ولا أساس له من الصحة.',
    image: 'https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-13',
    category: 'أخبار محلية',
    readTime: '4 دقائق',
    tags: ['مطران', 'حماة', 'نيقولا بعلبكي', 'قوات أمنية'],
    views: 11200,
    featured: false
  },
  {
    id: '2507231650',
    title: 'هذا الفيديو ليس جريمة إعدام ميداني بحق مدنيين من البدو.. تعرف على حقيقته',
    summary: 'نشر حساب في إنستغرام مقطع فيديو زعم أنه يُظهر عناصر "ميليشيات الهجري" تجمع مدنيين من البدو وتعدمهم ميدانياً في أحد الساحات العامة، غير أن الادعاء يتضمن معلومات مضللة.',
    verdict: 'misleading',
    subVerdict: 'تلاعب بالحقائق',
    subVerdictExplanation: 'المحتوى الذي يعتمد على حقائق لكن يتم توظيفها في سياق غير صحيح بما يؤدي إلى عكس هذه الحقائق.',
    image: 'https://images.pexels.com/photos/1550337/pexels-photo-1550337.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-23',
    category: 'أخبار محلية',
    readTime: '7 دقائق',
    tags: ['فيديو', 'إعدام', 'بدو', 'ميليشيات'],
    views: 18350,
    featured: true
  },
  {
    id: '2507111650',
    title: 'جدل حول تعديل صفة الفلسطينيين السوريين ومصادر حكومية تنفي',
    summary: 'انتشر جدل حول تعديل صفة الفلسطينيين السوريين في الوثائق الرسمية، لكن المصادر الحكومية نفت هذه المعلومات وأكدت عدم وجود أي تعديلات على الوثائق.',
    verdict: 'false',
    subVerdict: 'خطأ',
    subVerdictExplanation: 'المحتوى الذي يتضمن معلومات خاطئة شرط أن لا تؤثر على المحتوى بالكامل.',
    image: 'https://images.pexels.com/photos/3184416/pexels-photo-3184416.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-11',
    category: 'سياسة',
    readTime: '5 دقائق',
    tags: ['فلسطينيون', 'سوريون', 'وثائق', 'حكومة'],
    views: 13400,
    featured: false
  },
  {
    id: '2507011650',
    title: 'هل طُلي سور قلعة حلب باللون الأبيض؟',
    summary: 'انتشرت صور تزعم أن سور قلعة حلب تم طلاؤه باللون الأبيض، لكن التحقق أثبت أن هذه الصور قديمة ولا تمثل الوضع الحالي للقلعة.',
    verdict: 'false',
    subVerdict: 'خطأ',
    subVerdictExplanation: 'المحتوى الذي يتضمن معلومات خاطئة شرط أن لا تؤثر على المحتوى بالكامل.',
    image: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-01',
    category: 'ثقافة وتراث',
    readTime: '3 دقائق',
    tags: ['قلعة حلب', 'طلاء', 'أبيض', 'تراث'],
    views: 8900,
    featured: false
  },
  {
    id: '2506301650',
    title: 'هل صرح ترامب إنه سيرفع العقوبات عن سوريا إذا تحلّت بالسلام؟',
    summary: 'انتشرت ادعاءات حول تصريح من الرئيس الأمريكي السابق دونالد ترامب حول رفع العقوبات عن سوريا، لكن التحقق أثبت أن هذه المعلومات كاذبة ولم يصدر أي تصريح من هذا القبيل.',
    verdict: 'false',
    subVerdict: 'كذب',
    subVerdictExplanation: 'المحتوى الذي يتعارض بالكامل مع حقائق مثبتة وجرى تأليفه بالكامل ولا أساس له من الصحة.',
    image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-06-30',
    category: 'سياسة',
    readTime: '4 دقائق',
    tags: ['ترامب', 'عقوبات', 'سوريا', 'سلام'],
    views: 15600,
    featured: false
  },
  {
    id: '2508141651',
    title: 'هذا المقطع ليس لاستيلاء العشائر على مدرعة لقسد في منطقة غرانيج',
    summary: 'تداولت حسابات عبر فيسبوك وإكس مقطع فيديو زعمت أن يُظهر استيلاء العشائر على مدرعة لقسد في غرانيج، غير أن هذا الادعاء مضلل.',
    verdict: 'misleading',
    subVerdict: 'خارج السياق',
    subVerdictExplanation: 'المحتوى القديم الصحيح الذي يُستحضر مع حدث جديد مشابه، بحيث يظهر المحتوى القديم على أنه جزء من الحدث الجديد.',
    image: 'https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-14',
    category: 'أخبار محلية',
    readTime: '5 دقائق',
    tags: ['عشائر', 'مدرعة', 'قسد', 'غرانيج'],
    views: 12300,
    featured: false
  },
  {
    id: '2508011650',
    title: 'صور أفيخاي أدرعي في ريف دمشق لا تثبت دخوله مدينة قطنا',
    summary: 'انتشرت صور تزعم وجود المتحدث باسم الجيش الإسرائيلي أفيخاي أدرعي يتجول في قرى درزية قرب جبل الشيخ، وسط ادعاءات حول دخوله مدينة قطنا، مما أثار جدلاً واسعاً حول صحة هذه المعلومات.',
    verdict: 'unproven',
    subVerdict: 'غير مؤكد',
    subVerdictExplanation: 'المحتوى الذي لا يملك مقاومات كافية لتأكيده ولا لنفيه وتصنيفه ضمن أي نوع من أنواع التقييمات.',
    image: 'https://images.pexels.com/photos/1202723/pexels-photo-1202723.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-01',
    category: 'سياسة',
    readTime: '5 دقائق',
    tags: ['السويداء', 'الهجمات الإسرائيلية', 'أفيخاي أدرعي'],
    views: 12420,
    featured: true
  },
  {
    id: '2507230629',
    title: 'هل عُثر على جثة مدير مركز الدفاع المدني في السويداء المختطف "حمزة العمارين"؟',
    summary: 'تداولت منصات التواصل الاجتماعي ادعاءات حول العثور على جثة مدير مركز الدفاع المدني المختطف في السويداء، لكن هذه الادعاءات لم تؤكدها المصادر الرسمية.',
    verdict: 'unproven',
    subVerdict: 'غير مؤكد',
    subVerdictExplanation: 'المحتوى الذي لا يملك مقاومات كافية لتأكيده ولا لنفيه وتصنيفه ضمن أي نوع من أنواع التقييمات.',
    image: 'https://images.pexels.com/photos/4792073/pexels-photo-4792073.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-23',
    category: 'أخبار محلية',
    readTime: '4 دقائق',
    tags: ['السويداء', 'الدفاع المدني السوري', 'اختطاف'],
    views: 8230,
    featured: false
  },
  {
    id: '2507141324',
    title: 'هذا المقطع قديم ولا يظهر توجه أرتال من دير الزور باتجاه السويداء',
    summary: 'انتشر مقطع فيديو مع ادعاء حول توجه قوافل من دير الزور نحو السويداء لطرد العصابات، لكن هذا الادعاء مضلل حيث أن المقطع قديم ولا علاقة له بالأحداث الحالية.',
    verdict: 'misleading',
    subVerdict: 'خارج السياق',
    subVerdictExplanation: 'المحتوى القديم الصحيح الذي يُستحضر مع حدث جديد مشابه، بحيث يظهر المحتوى القديم على أنه جزء من الحدث الجديد.',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-14',
    category: 'أخبار محلية',
    readTime: '4 دقائق',
    tags: ['الأنشطة العسكرية', 'الأقليات'],
    views: 6420,
    featured: false
  },
  {
    id: '2508171650',
    title: 'هجوم تحريضي على منصة "تأكد" عقب كشفها حقيقة مجزرة في السويداء',
    summary: 'قناة تيليغرام واسعة الانتشار تروّج لرواية مضللة تزعم أن "ميليشيا حكمت الهجري" قتلت نساء من العشائر في شهبا؛ تحقق "تأكد" يثبت أن الضحايا من عائلة درزية.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/3825539/pexels-photo-3825539.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-17',
    category: 'أخبار محلية',
    readTime: '8 دقائق',
    tags: ['تأكد', 'السويداء', 'مجزرة', 'تحريض'],
    views: 22400,
    featured: true
  },
  {
    id: '2508121650',
    title: 'وفاة "عبد الرحمن جعجول" بمخفر الكلاسة في حلب تثير تساؤلات ومطالب بالعدالة',
    summary: 'أكدت المصادر الرسمية وفاة المواطن عبد الرحمن جعجول في مخفر الكلاسة بحلب، مما أثار تساؤلات حول ظروف الوفاة ومطالب بالعدالة.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/4629633/pexels-photo-4629633.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-12',
    category: 'أخبار محلية',
    readTime: '6 دقائق',
    tags: ['حلب', 'مخفر الكلاسة', 'وفاة', 'عدالة'],
    views: 18700,
    featured: false
  },
  {
    id: '2508111650',
    title: 'بين الشهادات الرسمية والمعلومات غير الموثقة: ماذا جرى في مشفى السويداء الوطني؟',
    summary: 'تأكدت التقارير حول الأحداث التي وقعت في مشفى السويداء الوطني بناءً على الشهادات الرسمية والمصادر الموثوقة، مما يوضح الصورة الحقيقية لما جرى.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-11',
    category: 'أخبار محلية',
    readTime: '7 دقائق',
    tags: ['مشفى السويداء', 'شهادات رسمية', 'مصادر موثوقة'],
    views: 16500,
    featured: false
  },
  {
    id: '2508081130',
    title: 'كيف يضلل نموذج Grok مستخدمي "إكس"؟ منصة "تأكد" تكشف إحدى تجاربها',
    summary: 'مؤخراً، يلجأ مستخدمو مواقع التواصل الاجتماعي بشكل متزايد إلى أدوات الذكاء الاصطناعي للتحقق من مقاطع الفيديو والصور والأخبار المتداولة، لكن هذه الأدوات قد تقدم معلومات مضللة.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/3825539/pexels-photo-3825539.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-08',
    category: 'تكنولوجيا',
    readTime: '6 دقائق',
    tags: ['ذكاء اصطناعي', 'Grok', 'تضليل رقمي'],
    views: 18320,
    featured: true
  },
  {
    id: '3',
    title: 'حرائق متواصلة في اللاذقية ومؤشرات "فعل متعمد"',
    summary: 'اندلعت حرائق في عدة مناطق بمحافظة اللاذقية، وتشير التقارير الأولية إلى وجود مؤشرات على أن بعض هذه الحرائق قد يكون مفتعلاً، لكن التحقيقات لا تزال جارية.',
    verdict: 'unproven',
    subVerdict: 'غير مؤكد',
    subVerdictExplanation: 'المحتوى الذي لا يملك مقاومات كافية لتأكيده ولا لنفيه وتصنيفه ضمن أي نوع من أنواع التقييمات.',
    image: 'https://images.pexels.com/photos/266487/pexels-photo-266487.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2024-12-12',
    category: 'بيئة وأمان',
    readTime: '5 دقائق',
    tags: ['حرائق', 'اللاذقية', 'بيئة'],
    views: 9150,
    featured: false
  },
  {
    id: '5',
    title: 'إدعاء إصابات في صفوف القوات الروسية بريف إدلب',
    summary: 'تداولت صفحات على مواقع التواصل الاجتماعي ادعاءات حول سقوط إصابات في صفوف القوات الروسية في منطقة ريف إدلب، لكن لم يتم التأكد من صحة هذه المعلومات من مصادر موثوقة.',
    verdict: 'unproven',
    subVerdict: 'غير مؤكد',
    subVerdictExplanation: 'المحتوى الذي لا يملك مقاومات كافية لتأكيده ولا لنفيه وتصنيفه ضمن أي نوع من أنواع التقييمات.',
    image: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2024-12-08',
    category: 'أخبار محلية',
    readTime: '3 دقائق',
    tags: ['إدلب', 'قوات روسية', 'إدعاء'],
    views: 7230,
    featured: false
  },
  {
    id: '6',
    title: 'صور تظهر تضرر مشافي في ريف دمشق الشرقي قديمة',
    summary: 'انتشرت صور تزعم أنها تظهر تضرر مشافي في منطقة الغوطة الشرقية بريف دمشق نتيجة قصف حديث، لكن تبين أن الصور قديمة تعود لفترات سابقة من النزاع.',
    verdict: 'misleading',
    subVerdict: 'خارج السياق',
    subVerdictExplanation: 'المحتوى القديم الصحيح الذي يُستحضر مع حدث جديد مشابه، بحيث يظهر المحتوى القديم على أنه جزء من الحدث الجديد.',
    image: 'https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2024-12-06',
    category: 'أخبار محلية',
    readTime: '4 دقائق',
    tags: ['ريف دمشق', 'مشافي', 'صور قديمة'],
    views: 4850,
    featured: false
  },
  {
    id: '7',
    title: 'ادعاءات حول انقطاع التيار الكهربائي في حمص غير دقيقة',
    summary: 'تداولت منشورات على مواقع التواصل الاجتماعي ادعاءات حول انقطاع التيار الكهربائي بشكل كامل في مدينة حمص لمدة 48 ساعة، لكن المؤسسة العامة للكهرباء نفت هذه المعلومات.',
    verdict: 'false',
    subVerdict: 'كذب',
    subVerdictExplanation: 'المحتوى الذي يتعارض بالكامل مع حقائق مثبتة وجرى تأليفه بالكامل ولا أساس له من الصحة.',
    image: 'https://images.pexels.com/photos/1550337/pexels-photo-1550337.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2024-12-04',
    category: 'أخبار محلية',
    readTime: '3 دقائق',
    tags: ['حمص', 'كهرباء', 'انقطاع'],
    views: 6780,
    featured: false
  },
  {
    id: '9',
    title: 'مصادر موثقة: مؤكد بناءً على مصادر علمية معتبرة',
    summary: 'تم الاعتماد على مصادر علمية معتبرة في التحقق من هذه المعلومة وفقاً لمعايير التحقق الدولية.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/3184416/pexels-photo-3184416.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2024-12-18',
    category: 'تحقق معتمد',
    readTime: '4 دقائق',
    tags: ['مصادر موثقة', 'علمي', 'معتمد'],
    views: 12450,
    featured: false
  },
  {
    id: '10',
    title: 'مراجع متخصص: تمت مراجعته من قبل خبراء في المجال',
    summary: 'تمت مراجعته من قبل خبراء في المجال وفقاً لمعايير التحقق الدولية.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2024-12-17',
    category: 'تحقق معتمد',
    readTime: '3 دقائق',
    tags: ['خبراء', 'مراجعة', 'متخصص'],
    views: 9870,
    featured: false
  },
  {
    id: '11',
    title: 'معايير دولية: وفقاً لمعايير التحقق الدولية',
    summary: 'تم التحقق من هذه المعلومة وفقاً لمعايير التحقق الدولية المعتمدة من IFCN.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2024-12-16',
    category: 'تحقق معتمد',
    readTime: '4 دقائق',
    tags: ['معايير دولية', 'IFCN', 'تحقق'],
    views: 8650,
    featured: false
  },
  {
    id: '13',
    title: 'ادعاءات حول وصول مساعدات دولية إلى درعا غير صحيحة',
    summary: 'انتشرت تقارير تزعم وصول مساعدات إنسانية دولية إلى مناطق في محافظة درعا، لكن المنظمات الإنسانية العاملة في المنطقة أكدت عدم صحة هذه المعلومات وأن آخر شحنة مساعدات وصلت قبل أشهر.',
    verdict: 'false',
    subVerdict: 'كذب',
    subVerdictExplanation: 'المحتوى الذي يتعارض بالكامل مع حقائق مثبتة وجرى تأليفه بالكامل ولا أساس له من الصحة.',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2024-12-02',
    category: 'أخبار محلية',
    readTime: '5 دقائق',
    tags: ['درعا', 'مساعدات إنسانية', 'منظمات دولية'],
    views: 8920,
    featured: true
  },
  {
    id: '14',
    title: 'الحكومة السورية تؤكد رسمياً بدء إعادة إعمار المناطق المتضررة',
    summary: 'أعلنت الحكومة السورية رسمياً عن بدء برنامج شامل لإعادة إعمار المناطق المتضررة في عدة محافظات بالتعاون مع المنظمات الدولية.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2024-12-19',
    category: 'سياسة',
    readTime: '5 دقائق',
    tags: ['إعمار', 'حكومة', 'سوريا'],
    views: 12500,
    featured: true
  },
  {
    id: '15',
    title: 'البنك المركزي السوري يؤكد استقرار سعر الصرف وتحسن الوضع الاقتصادي',
    summary: 'أكد البنك المركزي السوري في بيان رسمي استقرار سعر الصرف وتحسن مؤشرات الاقتصاد الكلي بعد سلسلة من الإجراءات الاقتصادية.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/4386370/pexels-photo-4386370.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2024-12-18',
    category: 'اقتصاد',
    readTime: '4 دقائق',
    tags: ['اقتصاد', 'بنك مركزي', 'عملة'],
    views: 10800,
    featured: false
  },
  {
    id: '2508071245',
    title: 'هذه الصورة ليست لتخريج دفعة جديدة من الجيش السوري',
    summary: 'تداولت على فيسبوك وإكس صورة زُعم أنها تظهر "تخريج جديد من الجيش الأموي"، لكن هذا الادعاء مضلل حيث تبين أن الصورة لا تمت بصلة للجيش السوري الحديث.',
    verdict: 'misleading',
    image: 'https://images.pexels.com/photos/3952224/pexels-photo-3952224.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-07',
    category: 'أخبار محلية',
    readTime: '5 دقائق',
    tags: ['الجيش السوري', 'صور مضللة', 'تخريج عسكري'],
    views: 11200,
    featured: false
  },
  {
    id: '2508061130',
    title: 'هل هو إنقاذ أم اختطاف؟ القصة الكاملة لعائلة السويداء في فيديو مثير',
    summary: 'انتشر فيديو مثير للجدل يظهر مشهداً لعائلة من السويداء، مما أثار تساؤلات حول طبيعة الحادثة وما إذا كانت عملية إنقاذ أم شيئاً آخر، مما يتطلب توضيحاً شاملاً للقصة.',
    verdict: 'misleading',
    image: 'https://images.pexels.com/photos/5905445/pexels-photo-5905445.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-06',
    category: 'أخبار محلية',
    readTime: '7 دقائق',
    tags: ['السويداء', 'فيديو مثير', 'قصة كاملة'],
    views: 9900,
    featured: false
  },
  // Additional articles for complete sections
  {
    id: '18',
    title: 'ما حقيقة إلغاء قانون قيصر بعد رفع العقوبات الأمريكية؟',
    summary: 'انتشرت ادعاءات حول إلغاء قانون قيصر ورفع العقوبات الأمريكية عن سوريا، لكن الحقيقة أن هذه المعلومات مؤكدة من المصادر الرسمية الأمريكية.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-23',
    category: 'سياسة',
    readTime: '6 دقائق',
    tags: ['قانون قيصر', 'عقوبات', 'سياسة دولية'],
    views: 15600,
    featured: false
  },
  {
    id: '19',
    title: 'جريمة رمي ثلاثة شبان من شرفة منزلهم وقعت في السويداء',
    summary: 'تأكدت التقارير حول وقوع جريمة بشعة في السويداء حيث تم رمي ثلاثة شبان من شرفة منزلهم، وقد أكدت المصادر الرسمية تفاصيل هذه الحادثة المأساوية.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/4629633/pexels-photo-4629633.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-20',
    category: 'أخبار محلية',
    readTime: '5 دقائق',
    tags: ['السويداء', 'جريمة', 'أمن'],
    views: 13200,
    featured: false
  },
  {
    id: '20',
    title: 'كيف تحول هاشتاغ "متضامن مع السويداء" إلى حملة سخرية؟',
    summary: 'رصد فريق تأكد كيف تحول هاشتاغ التضامن مع السويداء إلى حملة سخرية على منصات التواصل الاجتماعي، مما يؤكد التلاعب بالرأي العام الرقمي.',
    verdict: 'confirmed',
    image: 'https://images.pexels.com/photos/4348401/pexels-photo-4348401.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-29',
    category: 'وسائل التواصل',
    readTime: '4 دقائق',
    tags: ['هاشتاغ', 'تلاعب رقمي', 'السويداء'],
    views: 11800,
    featured: false
  },
  {
    id: '21',
    title: 'ادعاءات كاذبة حول تسريب امتحانات الثانوية العامة',
    summary: 'انتشرت ادعاءات عبر مجموعات واتساب حول تسريب أسئلة امتحانات الثانوية العامة، لكن وزارة التربية نفت هذه الادعاءات بشكل قاطع وأكدت سلامة الامتحانات.',
    verdict: 'false',
    image: 'https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-15',
    category: 'تعليم',
    readTime: '4 دقائق',
    tags: ['تسريب امتحانات', 'ثانوية عامة', 'تعليم'],
    views: 14200,
    featured: false
  },
  {
    id: '22',
    title: 'فيديو مفبرك يزعم انهيار جسر في حماة',
    summary: 'انتشر فيديو يزعم انهيار أحد الجسور الرئيسية في مدينة حماة، لكن التحقق أثبت أن الفيديو مفبرك ومأخوذ من حادثة قديمة في بلد آخر.',
    verdict: 'false',
    image: 'https://images.pexels.com/photos/2885320/pexels-photo-2885320.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-02',
    category: 'أخبار محلية',
    readTime: '3 دقائق',
    tags: ['فيديو مفبرك', 'حماة', 'بنية تحتية'],
    views: 10300,
    featured: false
  },
  {
    id: '23',
    title: 'ادعاءات خاطئة حول إغلاق مطار دمشق الدولي',
    summary: 'تداولت مواقع التواصل معلومات كاذبة حول إغلاق مطار دمشق الدولي لأسباب أمنية، لكن إدارة المطار أكدت استمرار العمل بشكل طبيعي.',
    verdict: 'false',
    image: 'https://images.pexels.com/photos/2026324/pexels-photo-2026324.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-28',
    category: 'نقل ومواصلات',
    readTime: '3 دقائق',
    tags: ['مطار دمشق', 'إغلاق', 'أخبار كاذبة'],
    views: 8900,
    featured: false
  },
  {
    id: '24',
    title: 'معلومات مغلوطة حول رفع أسعار المحروقات',
    summary: 'انتشرت شائعات حول رفع كبير في أسعار المحروقات دون إعلان رسمي، لكن وزارة النفط نفت هذه المعلومات وأكدت عدم وجود تغيير في الأسعار.',
    verdict: 'false',
    image: 'https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-01',
    category: 'اقتصاد',
    readTime: '3 دقائق',
    tags: ['محروقات', 'أسعار', 'شائعات'],
    views: 12100,
    featured: false
  },
  {
    id: '25',
    title: 'صور مضللة لتظاهرات في درعا من فترات سابقة',
    summary: 'انتشرت صور تزعم أنها لتظاهرات حديثة في درعا، لكن التحقق أثبت أن هذه الصور قديمة ومأخوذة من أحداث سابقة، مما يجعلها مضللة في السياق الحالي.',
    verdict: 'misleading',
    image: 'https://images.pexels.com/photos/3692618/pexels-photo-3692618.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-25',
    category: 'أخبار محلية',
    readTime: '4 دقائق',
    tags: ['درعا', 'صور مضللة', 'تظاهرات'],
    views: 9800,
    featured: false
  },
  {
    id: '26',
    title: 'فيديو قديم يُستخدم لادعاءات حول أوضاع في حلب',
    summary: 'تم تداول فيديو قديم على أنه يظهر أوضاع حديثة في مدينة حلب، لكن التحقق كشف أن المقطع من عام 2019 ولا علاقة له بالأحداث المزعومة.',
    verdict: 'misleading',
    image: 'https://images.pexels.com/photos/4553618/pexels-photo-4553618.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-03',
    category: 'أخبار محلية',
    readTime: '5 دقائق',
    tags: ['حلب', 'فيديو قديم', 'سياق خاطئ'],
    views: 7600,
    featured: false
  },
  {
    id: '27',
    title: 'تقارير غير مؤكدة حول فتح معبر جديد مع الأردن',
    summary: 'تداولت مصادر إعلامية تقارير حول فتح معبر حدودي جديد مع الأردن، لكن السلطات الحدودية لم تؤكد هذه المعلومات وتبقى قيد التحقق.',
    verdict: 'unproven',
    image: 'https://images.pexels.com/photos/4792073/pexels-photo-4792073.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-30',
    category: 'سياسة',
    readTime: '3 دقائق',
    tags: ['معابر حدودية', 'الأردن', 'غير مؤكد'],
    views: 6700,
    featured: false
  },
  {
    id: '28',
    title: 'ادعاءات حول اكتشاف مخزون أثري جديد غير موثقة',
    summary: 'انتشرت أنباء حول اكتشاف مخزون أثري كبير في منطقة تدمر، لكن وزارة السياحة والآثار لم تصدر بياناً رسمياً حول هذا الموضوع.',
    verdict: 'unproven',
    image: 'https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-08-04',
    category: 'ثقافة وتراث',
    readTime: '4 دقائق',
    tags: ['آثار', 'تدمر', 'اكتشافات'],
    views: 5900,
    featured: false
  },
  {
    id: '29',
    title: 'معلومات غير محققة حول برنامج دعم جديد للمزارعين',
    summary: 'تداولت منصات التواصل معلومات حول إطلاق برنامج دعم جديد للمزارعين، لكن وزارة الزراعة لم تعلن رسمياً عن تفاصيل هذا البرنامج.',
    verdict: 'unproven',
    image: 'https://images.pexels.com/photos/2886937/pexels-photo-2886937.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'فريق تأكد',
    date: '2025-07-22',
    category: 'اقتصاد',
    readTime: '3 دقائق',
    tags: ['زراعة', 'دعم حكومي', 'مزارعين'],
    views: 7200,
    featured: false
  }
];

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'أساسيات التحقق من المعلومات',
    description: 'تعلم المهارات الأساسية للتحقق من صحة المعلومات والأخبار على الإنترنت باستخدام الأدوات والتقنيات الحديثة.',
    duration: '4 أسابيع',
    level: 'مبتدئ',
    image: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=800',
    students: 1250,
    rating: 4.8,
    instructor: 'د. أحمد محمود'
  },
  {
    id: 'course-2',
    title: 'التحليل المتقدم للمحتوى المرئي',
    description: 'طرق متقدمة لتحليل الصور ومقاطع الفيديو والتحقق من أصالتها باستخدام التقنيات الرقمية المتطورة.',
    duration: '6 أسابيع',
    level: 'متقدم',
    image: 'https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=800',
    students: 890,
    rating: 4.9,
    instructor: 'سارة أحمد'
  },
  {
    id: 'course-3',
    title: 'صحافة البيانات والتحقق الإحصائي',
    description: 'تعلم كيفية تحليل البيانات والإحصائيات والتحقق من صحتها في السياق الصحفي.',
    duration: '5 أسابيع',
    level: 'متوسط',
    image: 'https://images.pexels.com/photos/590022/pexels-photo-590022.jpg?auto=compress&cs=tinysrgb&w=800',
    students: 670,
    rating: 4.7,
    instructor: 'محمد العلي'
  },
  {
    id: 'course-4',
    title: 'التحقق من المصادر الرقمية',
    description: 'دليل شامل للتحقق من موثوقية المصادر الرقمية وتقييم مصداقية المواقع الإلكترونية.',
    duration: '3 أسابيع',
    level: 'مبتدئ',
    image: 'https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=800',
    students: 1450,
    rating: 4.6,
    instructor: 'د. فاطمة الزهراء'
  }
];

export const categories = [
  'جميع الفئات',
  'سياسة',
  'أخبار محلية',
  'بيئة وأمان',
  'تعليم',
  'تكنولوجيا',
  'اقتصاد',
  'رياضة',
  'ثقافة'
];

export const verdictOptions = [
  'جميع التصنيفات',
  'احتيال',
  'عبث',
  'إرباك',
  'مؤكد'
];

export const verdictSubcategories = {
  'احتيال': [
    'كذب',
    'تضليل', 
    'نظرية المؤامرة',
    'كذب باسم العلم'
  ],
  'عبث': [
    'انحياز',
    'تلاعب بالحقائق',
    'خطأ'
  ],
  'إرباك': [
    'غير مؤكد',
    'عنوان مضلل', 
    'سخرية',
    'خارج السياق'
  ],
  'مؤكد': []
};

export const subcategoryDefinitions = {
  // احتيال subcategories
  'كذب': 'المحتوى الذي يتعارض بالكامل مع حقائق مثبتة وجرى تأليفه بالكامل ولا أساس له من الصحة.',
  'تضليل': 'المحتوى الذي يتضمن مزيجاً من الحقائق والأكاذيب.',
  'نظرية المؤامرة': 'المحتوى الذي يحرص على تضمين خطط خفية لمؤامرة ما ويقوم بالبناء على هذا الأساس بما يدعم توجها ما أو استنتاجا ما، دون أدلة أو قرائن واضحة ومثبتة.',
  'كذب باسم العلم': 'المحتوى الذي يتذرع بالعلِم من خلال شواهد غير مثبتة أو "نظريات علمية" غير صحيحة أو يسعى إلى تحريف تفسير علمي صحيح لجذب اهتمام الجمهور.',
  
  // عبث subcategories
  'خطأ': 'المحتوى الذي يتضمن معلومات خاطئة شرط أن لا تؤثر على المحتوى بالكامل.',
  'انحياز': 'المحتوى الانتقائي والذي يتضمن اجتزاء للحقائق أو تفضيل حقائق بعينها منزوعة من سياقها العام.',
  'تلاعب بالحقائق': 'المحتوى الذي يعتمد على حقائق لكن يتم توظيفها في سياق غير صحيح بما يؤدي إلى عكس هذه الحقائق.',
  
  // إرباك subcategories
  'عنوان مضلل': 'المحتوى الذي يتضمن معلومات يوحي فيها العنوان بمحتوى مختلف عن المتن، مثل العناوين الصفراء الهادفة إلى جذب الجمهور.',
  'سخرية': 'المحتوى الذي يستخدم الخيال و/أو التمثيل الساخر للواقع مع الإشارة إلى ذلك في المحتوى الأصلي وإغفاله في حال إعادة النشر.',
  'خارج السياق': 'المحتوى القديم الصحيح الذي يُستحضر مع حدث جديد مشابه، بحيث يظهر المحتوى القديم على أنه جزء من الحدث الجديد.',
  'غير مؤكد': 'المحتوى الذي لا يملك مقاومات كافية لتأكيده ولا لنفيه وتصنيفه ضمن أي نوع من أنواع التقييمات.'
};

export const dateRanges = [
  'جميع التواريخ',
  'آخر يوم',
  'آخر أسبوع',
  'آخر شهر',
  'آخر 3 أشهر',
  'آخر سنة'
];

export const sortOptions = [
  'الأحدث',
  'الأقدم',
  'الأكثر مشاهدة',
  'الأقل مشاهدة'
];